[package]
name = "dig/parallel"
description = "Parallel execution library for Roblox lua"
version = "1.0.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]

[dependencies]
Promise = "evaera/promise@4.0.0"